version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./html:/usr/share/nginx/html
    deploy:
      replicas: 2  # Scale nginx service to 3 replicas
      placement:
        constraints: [node.role == worker]  # Only deploy on worker nodes

  app:
    build: ./app
    ports:
      - "3000:3000"
    volumes:
      - ./app:/usr/src/app
    environment:
      - NODE_ENV=production
    deploy:
      replicas: 2  # Scale app service to 2 replicas
      resources:
        limits:
          cpus: '0.5'  # Limit CPU usage for each container
          memory: '1024M'  # Limit memory usage for each container

